### ISSUE TITLE
请问在 Android 端报 create model resources dir failed 是什么原因？

### ISSUE THREAD

**Issue by Kennytian** [wayne214/react-native-baidu-voice#2]
```
2019-11-08 11:25:09.246 13721-13721/com.china.myapp E/SoLoader: couldn't find DSO to load: libjscexecutor.so
2019-11-08 11:25:18.638 13721-13799/com.china.myapp E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: create model resources dir failed :/storage/emulated/0/Android/data/com.china.myapp/files/baiduTTS
        at com.wayne.baiduvoice.util.FileUtil.createTmpDir(FileUtil.java:25)
        at com.wayne.baiduvoice.util.OfflineResource.<init>(OfflineResource.java:41)
        at com.wayne.baiduvoice.VoiceUtils.createOfflineResource(VoiceUtils.java:184)
        at com.wayne.baiduvoice.VoiceUtils.getParams(VoiceUtils.java:173)
        at com.wayne.baiduvoice.VoiceUtils.initialTts(VoiceUtils.java:83)
        at com.wayne.baiduvoice.VoiceUtils.init(VoiceUtils.java:65)
        at com.wayne.baiduvoice.RNBaiduvoiceModule.initBaiduTTS(RNBaiduvoiceModule.java:32)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2019-11-08 11:25:18.653 13721-13799/com.china.myapp E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.wayne.baiduvoice.control.MySyntherizer.speak(java.lang.String)' on a null object reference
        at com.wayne.baiduvoice.VoiceUtils.speak(VoiceUtils.java:61)
        at com.wayne.baiduvoice.RNBaiduvoiceModule.speak(RNBaiduvoiceModule.java:37)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)

```

**Comment by wayne214** [comment]
请问，你的rn版本是多少？是否配置有问题呢？

**Comment by wayne214** [comment]
你可以看看这个issue,看看是不是Android的环境问题https://stackoverflow.com/questions/57166876/update-to-react-0-60-4-breaks-android-build-error-cannot-find-symbol

**Comment by Kennytian** [comment]
> 请问，你的rn版本是多少？是否配置有问题呢？

@wayne214 
```
System:
    OS: macOS 10.15.1
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 16, 21, 23, 25, 28, 29
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```

**Comment by Kennytian** [comment]
> 你可以看看这个issue,看看是不是Android的环境问题https://stackoverflow.com/questions/57166876/update-to-react-0-60-4-breaks-android-build-error-cannot-find-symbol

@wayne214  谢谢回复，不是这个问题
